server:
  port: 7000

eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:7001/eureka/
spring:
  profiles: peer2