server:
  port: 8761
eureka:
  instance:
    hostname:localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      dafaultZone: http://${eureka_server.instance.hostname}:${server.port}/eureka_server/
