server:
  port: 7008
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weinh/SpringcloudConfig/
          search-paths: respo
      label: master
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/