spring:
  application:
    name: service-turbine
server:
  port: 7012
security:
  basic:
    enabled: false
turbine:
  appConfig: service-feign,service-ribbon
  clusterNameExpression: "'default'"
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/